[package]
name = "git-tree"
version = "0.1.3"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
clap = "2.33.0"
failure = "0.1.1"
git2 = "0.11.0"
