[package]
name = "git-tree"
version = "0.1.4"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.31"
clap = "2.33.1"
git2 = "0.13.6"
