[package]
name = "git-tree"
version = "0.1.5"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>"]
edition = "2021"
description = "tree + git status: displays git status info in a tree"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.86"
# We vendor OpenSSL. If we do not, compilation will fail on recent (as of
# January 2023) Ubuntu systems.
git2 = { version = "0.19.0", features = ["vendored-openssl"] }
clap = { version = "4", features = [ "derive", "wrap_help" ] }
