on: push

name: Build and test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        rust: [ stable ]

    name: ${{ matrix.os }}, Rust ${{ matrix.rust }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust (rustup)
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt
        rustc --version
      shell: bash

    - name: Build (release)
      run: cargo build --verbose --release

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Test
      run: cargo test
