# This is a condensed version of [release-yml].
#
# [release-yml]: https://github.com/paskausks/rust-bin-github-workflows/blob/894a4f2debade42f8d7b5b95f493eaa33fdeb81b/.github/workflows/release.yml
on: push

name: Create release for Windows

jobs:
  build:
    name: Build release

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [windows]
        include:
          - build: windows
            os: windows-latest
            rust: stable

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash

    - name: Build
      run: cargo build --verbose --release

    - uses: actions/upload-artifact@v1
      name: Upload binary
      with:
        name: ${{ runner.os }}
        path: target/release/git-tree.exe
